  name: Deploy to github pages
  on:
    push:
      branches:
        - master
  jobs:
    gh-pages-deploy:
      name: Deploying to gh-pages
      runs-on: ubuntu-latest
      steps:
        - name: Checkout branch
          uses: actions/checkout@v4
        - name: Setup Node.js for use with actions
          uses: actions/setup-node@v4
        - name: Clean install dependencies
          run: yarn install --immutable --immutable-cache --check-cache

        - name: Run deploy script
          run: |
            git config user.name "AutoBot" && git config user.email "autobot@autobot.com"
            npm run gh-pages-deploy